version: '3'
services:
services:
  dynamodb:
    image: savaki/dynamodb:latest
    ports:
      - "8000:8000"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 172.19.131.93
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
